### ISSUE TITLE
Tab bar opacity?

### ISSUE THREAD

**Issue by haleyngonadi** [ezescaruli/ESTabBarController#3] opened 2015-09-16 08:11 UTC
Thanks for sharing this amazing control. It's exactly what I needed. I'm having a bit of an issue. The tab bar isn't 100% the color I set it, it's a bit brighter and I want it to be the exact color, no transparency. Where can I change/fix this? Thanks in advance.

**Comment by ezescaruli** [comment] 2015-09-19 01:54
Hey @haleyngonadi! Nice that you like the control, thanks :)

At the moment, the colors that you can set are the following:
- `selectedColor`: The color of the selection indicator, and the one that is applied to a button when it's selected.
- `buttonsBackgroundColor`: The background color of the buttons container.
- `separatorLineColor`: The color of the line that separates the buttons with the controllers inside the tab bar controller.

The color of the icons is not changed, so it should be the same that they have in your image assets.

To know a bit more about your issue, what is the color that is being a bit brighter?

**Comment by haleyngonadi** [comment] 2015-09-19 01:59
Thank you for replying. Here's an example: http://i.imgur.com/E2zAFJm.png The square in the background is set to the same color as the tab bar. Also the navigation bar color is the same as the one of the highlighted tab bar but for some reason, the colors don't end up the same :( 

Here are the hexes (#f26969 & #081a23) if you wanna check it out :)

**Comment by ezescaruli** [comment] 2015-09-19 06:54
@haleyngonadi I couldn't see anything that might change the opacity of the tab bar. May it be anything else changing the opacity of your inner view controller / navigation bar?

May you try setting both colors of the square and the tab bar to `[UIColor blackColor]`? Then we can check which one has the correct RGB of `(0.0, 0.0, 0.0).`

**Comment by haleyngonadi** [comment] 2015-09-19 18:35
I changed both to black color and they both had the right color. Odd. I wonder what it is when it comes to the other colors? But thanks for your help :)

**Comment by ezescaruli** [comment] 2015-09-20 07:57
@haleyngonadi That's weird. We could try with other color, say `[UIColor redColor]`. That should be a `(1.0, 0.0, 0.0)` in RGB.

**Comment by ezescaruli** [comment] 2016-05-04 23:26
@haleyngonadi I will close this one since we couldn't reproduce it. If you have further examples and any code that you can share to help reproducing it, let me know :)

**Closed as completed by ezescaruli** 2016-05-04 23:26 UTC
